### ISSUE TITLE
Bug Report 1,2,3: Different result of the same notes,  Making music application crushed, Not working 'drag file function'.

### ISSUE THREAD

**Issue by kimboho** [Vishwa061/2311-Group-12#11]
### 1. BugName : Different result of the same notes

Date -   23 Mar 2021

Description -   The same notes in text form have different results in the result score.

Steps to reproduce -   To upload files, click Select File. Click Convert to make the result XML file.

Expected result -   The same notes in the text file should have the same expression in the result XML file.
Actual result -   Exact the same notes have different results.

Screenshot:
example input
![image](https://user-images.githubusercontent.com/70533714/112354078-b984a280-8ca2-11eb-8f3b-f9b5f2c3e9f1.png)

But the different expressions in the result.
![image](https://user-images.githubusercontent.com/70533714/112354181-cef9cc80-8ca2-11eb-9ee2-3a1ea2256069.png)
One hammer-on was expressed and another hammer-on was not expressed.

Operating System -   Window10 Pro

Eclipse version -   Eclipse IDE for Enterprise Java Developers 4.18.0

Priority -   Low

Severity -   Low

### 2. BugName :  Making music application crushed

Date -   23 Mar 2021

Description -   Text input with invalid notes is converted to an XML file without notifying the error situation and it makes the music application crushed.

Steps to reproduce -   To upload files, click Select File. Click Convert to make the result XML file. Run the result file on the music application which supports music XML format.

Expected result -   With invalid notes, the system should pop up and show error messages (UserManual; 4.2 Invalid Inputs).

Actual result -  No error messages pop up and it completed converting. But the result file makes crushing in music application.

Screenshots:
![image](https://user-images.githubusercontent.com/70533714/112356194-b985a200-8ca4-11eb-8ef1-e8459e3e5fdc.png)
input file has invalid notes in text file.

![image](https://user-images.githubusercontent.com/70533714/112356264-cf936280-8ca4-11eb-86f1-d5cac54b55c1.png)
result without error message.

![image](https://user-images.githubusercontent.com/70533714/112356455-01a4c480-8ca5-11eb-8831-43be7d67bc5f.png)
When the result file is run, it makes a crush in the music application.

Operating System -   Window10 Pro

Eclipse version -   Eclipse IDE for Enterprise Java Developers 4.18.0

Priority -   High

Severity -   High

### 3. BugName :  Not working 'drag file function'

Date -   23 Mar 2021

Description -   Dragging the input file to the system is not working.

Steps to reproduce -   To upload files, click Select File. To test the dragging method(UserManual; 3.2 Selecting the File, Method2), drag the text file to the system.

Expected result -   The text file which is dragged is uploaded in the system and shows text information in the input box.

Actual result - Dragging file is prohibited. Failed to upload file using dragging.

Screenshots:
![cap](https://user-images.githubusercontent.com/70533714/112359445-a6280600-8ca7-11eb-8e2f-94648ce427c0.png)
Dragging file is not possible.

Operating System -   Window10 Pro

Eclipse version -   Eclipse IDE for Enterprise Java Developers 4.18.0

Priority -   High

Severity -   Low

**Comment by Sara-Araibi** [comment]
All features work now and all hammers are taken cared off
