### ISSUE TITLE
Conversion Bug

### ISSUE THREAD

**Issue by tens-ml** [Vishwa061/2311-Group-12#15]
<h1>Conversion Bug</h1>
<p> 
<b>Description:</b>  When a tab is input into the converter, it is incorrectly detected as a drum tab, and no output is produced.
</p>
<p> 
<b>Actual Behavior:</b>  Creates empty, incorrect score for drumset tab.
</p>
<p> 
<b>Expected Behavior:</b>  Creates valid score for guitar tab.
</p>
<p> 
<b>Steps to Reproduce:</b>  Input the attached tab for conversion and press convert without changing any of the default options
</p>
<p> 
<b>Priority:</b>  Very High
</p>
<p> 
<b>Status:</b>  Ready for development
</p>
<p>
<b>Images:</b>

![](https://i.imgur.com/SyqlavM.png)

</p>
<p>
<b>Input Text File:</b>

#1                          #2
  3/4                         4/4                                         3/4                         4/4
E{|---------------------------|-----------------------------------|	E||---------------------------|-----------------------------------|
B{|---0-------1-------3-------|---12----12--12----12----12--12----|	B||---0-------1-------3-------|---12----12--12----12----12--12----|
G{|-------0-------0-------0---|-------0-------0-------0-------0---|	G||.------0-------0-------0---|-------0-------0-------0-------0---|
D{|---------------------------|-----------------------------------|	D||.--------------------------|-----------------------------------|
A{|-----------0-------2-------|---10------10------10------10------|	A||-----------0-------2-------|---10------10------10------10------|
E{|---3-----------------------|-----------------------------------|	E||---3-----------------------|-----------------------------------|
      +   .   +   .   +   .       +   .   +   .   +   .   +   .		      +   .   +   .   +   .       +   .   +   .   +   .   +   .
									                                1. Blackbird singing in the dead of night
									                                2. Blackbird singing in the dead of night

  #5
      C       A7/C#   D       B7/D#       Em              Cm/Eb
E |-----------3---------------5-------|-----------------------------------|
B |---5--(5)----------7--(7)----------|---8-----8---8-----8-----8---8-----|
G |-------0-------0-------0-------0---|-------0-------0-------0-------0---|
D |-----------------------------------|-----------------------------------|
A |---3-------4-------5-------6-------|---7-------7-------6-------6-------|
E |-----------------------------------|-----------------------------------|
      +   .   +   .   +   .   +   .       +   .   +   .   +   .   +   .
      Take these broken wings and learn to fly
      Take these sunken eyes and learn to see  (notes in () not played 2nd verse)

  #7
  3/2
E |-----------3----------------------------------------|
B |---7---------------5-----5---5------4-----4---4-----|
G |-------0-------0-------0-------0--------0-------0---|
D |----------------------------------------------------|
A |---5-------4-------3-------3--------3-------3-------|
E |----------------------------------------------------|
      +       .       +       .        +       .
      All     your    life
      All     your    life

  #8
   3/2
E |----------------------------------------------------|
B |---3-----3---3-----2-----2---2------1-----1---1-----|
G |-------0-------0-------0-------0--------0-------0---|
D |------------------------------------0-------0-------|
A |---2-------2-------0-------0------------------------|
E |----------------------------------------------------|
      +       .       +       .        +       .
     You were only  waiting  for this  moment  to a-
     You were only  waiting  for this  moment  to be

   -----------------------------------------------------------------------...
  |  1.
  #9hi
  4/4
E |-----------------------------------|-----------------------------------|
B |---0-----0---0-----5-------3-------|---2-----2---2-----1-----1---1-----|
G |-------0-------0-------0-------0---|-------0-------0-------0-------0---|
D |-----------------------------------|-------------------0-------0-------|
A |-------------------3-------2-------|---0-------0-----------------------|
E |---3-------3-----------------------|-----------------------------------|
      +   .   +   .   +   .   +   .       +   .   +   .   +   .   +   .
      rise.

  ... -----------------  -------------------
                       ||  2.               |
  #11                  ||                   |
  2/2                   2/2
E |--------------------||-------------------|
B |---0-----0---0------||---0-----0---0-----|
G |-------0-------0---.||-------0-------0---|
D |-------------------.||-------------------|
A |--------------------||-------------------|
E |---3-------3--------||---3-------3-------|
      +   .   +   .         +   .   +   .
                             free.

  #13
  4/4
E |-----------------------------------|-------------------0-----0---0-----|
B |---10------8-------6-------5-------|---3-----3---3---------------------|
G |-------0-------0-------0-------0---|-------0-------0-------0-------0---|
D |-----------------------------------|-----------------------------------|
A |---8-------7-------5-------3-------|---1-------1-------3-------3-------|
E |-----------------------------------|-----------------------------------|
      +   .   +   .   +   .   +   .       +   .   +   .   +   .   +   .
      Black     -     bird,              fly,

  #15
  4/4
E |-----------------------------------|-----------------------------------|
B |---10------8-------6-------5-------|---3-----3---3-----2-----2---2-----|
G |-------0-------0-------0-------0---|-------0-------0-------0-------0---|
D |-----------------------------------|-----------------------------------|
A |---8-------7-------5-------3-------|---1-------1-------0-------0-------|
E |-----------------------------------|-----------------------------------|
      +   .   +   .   +   .   +   .       +   .   +   .   +   .   +   .
      Black     -     bird,              fly,                    into the

  #17
  2/4
E |----------------------|
B |---1-----1---1----1---|
G |-------0-------0------|
D |---0-------0----------|
A |----------------------|
E |----------------------|
      +   .   +   .
      light of a dark blackc

  #18
  3/4                         3/4
E |---------------------------|-----------------------------------|
B |---0-------1-------3-------|---12----12--12----12--12--12------|
G |-------0-------0-------0---|-------0-------0-------0-----------|
D |---------------------------|-----------------------------------|
A |-----------0-------2-------|---10------10------10------10------|
E |---3-----------------------|-----------------------------------|
      +   .   +   .   +   .       +   .   +   .   +   .   +   .
      night.

  #20
   3/4                                3/4
E |-----------3---------------5-------|-----------------------------------|
B |---5---5-----------7---7-----------|---8-----8-----8---8-----8---8-----|
G |-------0-------0-------0-------0---|-------0-----0---------0-------0---|
D |-----------------------------------|-----------------------------------|
A |---3-------4-------5-------6-------|---7-------7-------6-------6-------|
E |-----------------------------------|-----------------------------------|
      +   .   +   .   +   .   +   .       +   .   +   .   +   .   +   .

[ Tab from: https://www.guitartabs.cc/tabs/b/beatles/blackbird_tab_ver_12.html ]
  #22
  3/2
E |-----------3----------------------------------------|
B |---7---------------5-----5---5------4-----4---4-----|
G |-------0-------0-------0-------0--------0-------0---|
D |----------------------------------------------------|
A |---5-------4-------3-------3--------3-------3-------|
E |----------------------------------------------------|
      +       .       +       .        +       .

  #23                                                  #24
   3/2                                                 2/4
E |----------------------------------------------------|---------------|
B |---3-----3---3-----2-----2---2------1-----1---1-----|---0-----------|
G |-------0-------0-------0-------0--------0-------0---|---0-----------|
D |------------------------------------0-------0-------|---------------|
A |---2-------2-------0-------0------------------------|---------------|
E |----------------------------------------------------|---3-----------|
      +       .       +       .        +       .           +       .

  #25
  4/4
E |-----------------------------------|-------------------0-----0---0-----|
B |---10------8-------6-------5-------|---3-----3---3---------------------|
G |-------0-------0-------0-------0---|-------0-------0-------0-------0---|
D |-----------------------------------|-----------------------------------|
A |---8-------7-------5-------3-------|---1-------1-------3-------3-------|
E |-----------------------------------|-----------------------------------|
      +   .   +   .   +   .   +   .       +   .   +   .   +   .   +   .
      Black     -     bird,               fly,

  #27
  4/4
E |-----------------------------------|-----------------------------------|
B |---10------8-------6-------5-------|---3---3-------3---2-----2---2-----|
G |-------0-------0-------0-------0---|-------------0---------0-------0---|
D |-----------------------------------|-----------------------------------|
A |---8-------7-------5-------3-------|---1-------1-------0-------0-------|
E |-----------------------------------|-----------------------------------|
      +   .   +   .   +   .   +   .       +   .   +   .   +   .   +   .
      Black     -     bird,               fly,                    into the

  #29
  2/4
E |----------------------|
B |---1-----1---1----1---|
G |-------0-------0------|
D |---0-------0----------|
A |----------------------|
E |----------------------|
      +   .   +   .
    light of a dark, black

  #30
  3/4                         3/4
E |---------------------------|-----------------------------------|
B |---0-------1-------3-------|---12----12--12----12----12--12----|
G |---------------------------|-------0-------0-------0-------0---|
D |---------------------------|-----------------------------------|
A |-----------0-------2-------|-----------------------------------|
E |---3-----------------------|---10------10------10------10------|
      +   .   +   .   +   .       +   .   +   .   +   .   +   .
      night.

 #31
  3/4                                 3/4
E |-----------------------------------|-----------------------------------|
B |---12----12--12----12----12--12----|---12----12--12----12---------12/--|
G |-------0-------0-------0-------0---|-------0-------0---0---------------|
D |-----------------------------------|-----------------------------------|
A |---10------10------10------10------|---10------10------10---------10/--|
E |-----------------------------------|-----------------------------------|
      +   .   +   .   +   .       +   .   +   .   +   .   +   .   +   .
                                molto rit.

  #34
  3/4                            3/4
E||------------------------------|---0-----------------------|
B||------0-------1-------3-------|-----------3-------2-------|
G||----------0-------0-------0---|-------0-------0-------0---|
D||------------------------------|---------------------------|
A||--------------0-------2-------|---3-------2-------0-------|
E||---10\3-----------------------|---------------------------|
          +   .   +   .   +   .      +   .   +   .   +   .
 slide down
        a tempo

  #36
  2/4
E |------------------|
B |--1-----1---1-----|
G |------0-------0---|
D |--0-------0-------|
A |------------------|
E |------------------|
     +   .   +   .

  #37
  3/4                         4/4
E||---------------------------|-----------------------------------|
B||---0-------1-------3-------|---12----12--12----12----12--12----|
G||.------0-------0-------0---|-------0-------0-------0-------0---|
D||.--------------------------|-----------------------------------|
A||-----------0-------2-------|---10------10------10------10------|
E||---3-----------------------|-----------------------------------|
      +   .   +   .   +   .       +   .   +   .   +   .   +   .
    Blackbird singing in the dead of night

  #39
      C       A7/C#   D       B7/D#       Em              Cm/Eb
E |-----------3---------------5-------|-----------------------------------|
B |---5---------------7---7-----------|---8-----8---8-----8-----8---8-----|
G |-------0-------0-------0-------0---|-------0-------0-------0-------0---|
D |-----------------------------------|-----------------------------------|
A |---3-------4-------5-------6-------|---7-------7-------6-------6-------|
E |-----------------------------------|-----------------------------------|
      +   .   +   .   +   .   +   .       +   .   +   .   +   .   +   .
      Take these broken wings and learn to fly;

  #41
  3/2
E |-----------3----------------------------------------|
B |---7---------------5---5-------5----4---4-------4---|
G |-------0-------0---------0---0------------0---0-----|
D |----------------------------------------------------|
A |---5-------4-------3-------3--------3-------3-------|
E |----------------------------------------------------|
      +       .       +       .        +       .
      All     your    life

  #42
  4/4
E||-----------------------------------|-----------------------------------||
B||---3-----3---3-----2-----2---2-----|---1-----1---1-----0---------------||
G||.------0-------0-------0-------0---|-------0-------0---0--------------.||
D||.----------------------------------|---0-------0----------------------.||
A||---2-------2-------0-------0-------|-----------------------------------||
E||-----------------------------------|-------------------3---------------||
      +   .   +   .   +   .   +   .       +   .   +   .   +   .   +   .
     You were only   waiting  for this    moment  to    a-rise.

  #44
      C       G/B     A7                  C/D             G
E |-----------------------------------|-----------------------------------||}
B |---5-------3-------2-----2---2-----|---1-----1---1-----3---------------||}
G |-------0-------0-------0-------0---|-------0-------0---0---------------||}
D |-----------------------------------|---0-------0-------0---------------||}
A |---3-------2-------0-------0-------|-----------------------------------||}
E |-----------------------------------|-------------------3---------------||}
      +   .   +   .   +   .   +   .       +   .   +   .   +   .   +   .
     You were only   waiting  for this    moment  to    a-rise.

</p>

**Comment by Sara-Araibi** [comment]
Fixed, some errors are considered minor so it will still translate to an XML file and others will be considered a major error and cannot be converted. An error msg will be displayed
