### ISSUE TITLE
BUG: Output Showing Incorrect Instrument Type

### ISSUE THREAD

**Issue by tran28** [Vishwa061/2311-Group-12#16]
### Bug ID#:
12.2

### Reported By:
Phuong Tran (Matthew)

### Title:
Output showing drums tab when guitar tabs are inputted

### Platform:
Windows 10 Education
Eclipse IDE 2020-12
Java SE-15

### Version:
Commit 8f22041

### Reproduction:
Open the application, and select the following guitar sample files:
Input 1 | Input 2 | Input 3
------------ | ------------- | ------------- 
[guitar tab (standard major scale)](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/exampleemajor.txt) | [guitar tab (repeated measure)](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/examplerepeat.txt) | [guitar tab (grace note included)](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/graceexample.txt) | 

### Expected:
The XML output should detect the instrument type and/or present an option to choose the instrument. The system should then correctly do the conversion in the selected instrument type.

### Actual:
The instrument is automatically detected as drums and there is no option to change the instrument type. The XML output is also incorrect.

### Priority:
**High** - since the instrument type is incorrect, the file conversion output is incorrect

### Severity:
**High** - string instruments, such as guitar and bass, are one of the primary requirements of the system

### Screenshots
Input 1 | Input 2 | Input 3
------------ | ------------- | ------------- 
![image](https://user-images.githubusercontent.com/46450245/112398132-d8525b80-8cd9-11eb-9c70-0e6c52ca6758.png) | ![image](https://user-images.githubusercontent.com/46450245/112398353-64fd1980-8cda-11eb-91a3-f9f50416249e.png) | ![image](https://user-images.githubusercontent.com/46450245/112398474-adb4d280-8cda-11eb-8d1b-30e3e0d7c877.png)

_Click on the screenshots to view it in the original size._

**Comment by Sara-Araibi** [comment]
Recognizes the different instruments
