### ISSUE TITLE
BUG: Incorrect XML outputted when converted.

### ISSUE THREAD

**Issue by HappyNimbus** [Vishwa061/2311-Group-12#17]
**Reported By:**
Maksim Kolotev

**Version**
Commit: 8f22041

**Platform**
Windows 10
Java 15
Eclipse 4.18

**Reproduction:**
Following the procedure in the user manual, entering a basic tab, and clicking convert will show this bug.

**Expected:**
A guitar tab converted into MusicXML or XML that looks like the one on the class wiki (guitar example) in the viewing window.

**Actual:**
guitar tab converted to an empty drum tab in the viewing window.

**Priority**
High

**Severity**
High

This is a huge issue for users trying to use your program. If your program does not show the correct conversion the user will get confused and won't know what to do/assume that the program doesn't work.

![BUG1](https://user-images.githubusercontent.com/77296329/112401737-91686400-8ce1-11eb-9854-d4e9c241394c.PNG)

Guitar tab used:

[guitar.txt](https://github.com/Vishwa061/2311-Group-12/files/6201230/guitar.txt)

Outputted XML:

![TESTER](https://user-images.githubusercontent.com/77296329/112401882-d42a3c00-8ce1-11eb-834f-bc5a21488c3d.PNG)
![TESTER2](https://user-images.githubusercontent.com/77296329/112401917-ea37fc80-8ce1-11eb-9030-d4e72f6eccd0.PNG)

**Comment by Sara-Araibi** [comment]
Conversion fixed
