### ISSUE TITLE
BUG: Additional Features Do Not Modify Output

### ISSUE THREAD

**Issue by tran28** [Vishwa061/2311-Group-12#19]
### Bug ID#:
12.3

### Reported By:
Phuong Tran (Matthew)

### Title:
Additional features such as *Specify Title*, *Specify Composer*, *Select Key*, and *Select Time Signature* do not modify output

### Platform:
Windows 10 Education
Eclipse IDE 2020-12
Java SE-15

### Version:
Commit 8f22041

### Reproduction:
Open the application, select a file (could be any text tab file - I used this [guitar text tab](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/exampleemajor.txt)). Click *Show more features* and do the following:
1. Click *Specify Title* and change the title
2. Click *Specify Composer* and change the composer
3. Click *Select Key* and select a key
4.  Click *Select Time Signature* and select beat/beat time

### Expected:
XML output should include the user-inputted title, composer, key, and time signature changes.

### Actual:
User inputs for the title and composer are shown in the console. No system changes for key or time signature selection.

### Priority:
**Low** - these are additional features that are not primary requirements of the system

### Severity:
**Medium** - since it is an included feature and highly visible to the user, it should be correctly implemented as it dictates a reasonable part of the converted output (in which the customer had stated output correctness is important)

### Screenshot
https://user-images.githubusercontent.com/46450245/112403438-ccb86200-8ce4-11eb-998b-59ab87998b56.mov

**Comment by Sara-Araibi** [comment]
Issue has been resolved
