### ISSUE TITLE
BUG: No proper error message for none tabs

### ISSUE THREAD

**Issue by HappyNimbus** [Vishwa061/2311-Group-12#20]
**Reported By:**
Maksim Kolotev

**Version**
Commit: 8f22041

**Platform**
Windows 10
Java 15
Eclipse 4.18

**Reproduction:**
Enter a text file that not contain a music tab.

**Expected:**
The program will pop up an error saying that the input is not a correct tab and will ask you to either try again or exit.

**Actual:**
The program says the conversion was successful and proceeded to print something out in the XML viewer.

**Priority**
HIGH

**Severity**
HIGH

It appears that the program itself isn't actually detecting tabs properly and instead is constantly printing out a dummy drum tab regardless of the input. This seems to be the cause of most of the bugs coming up.

![BUG3](https://user-images.githubusercontent.com/77296329/112403603-1bfe9280-8ce5-11eb-92de-c37d921e2e00.PNG)

**Comment by Sara-Araibi** [comment]
Displays error message
