### ISSUE TITLE
Copy Paste & Drag and Drop functions not working

### ISSUE THREAD

**Issue by mike-jshen** [Vishwa061/2311-Group-12#21]
Report by: Mike Shen 216353583

Group 12 Bug Reports 

Version: 8f22041

Tested on: Windows 10 Java SE 1.8

Bug Report : Copy Paste & Drag and Drop functions not working.

Severity: High (Expected output is not achieved)

Description:
When manually copy pasting the text into the “Step 2” box, it seems like your program does not recognize the text. The drag and drop import method also seem to be broken.

Comments:
It seems like adding any sort of modification to the text box does not yield any sort of change to the xml output. This limits the user to only an import file. 

Attachments:
 
In this image, we see that the Convert button does not do anything when adding text manually
 
![image](https://user-images.githubusercontent.com/68671792/112405869-7e599200-8ce9-11eb-9a73-e3c85a694953.png)

In this image, we can see that the drag and drop feature is not supported. 
![image](https://user-images.githubusercontent.com/68671792/112405888-844f7300-8ce9-11eb-9973-4a3c1bb48b89.png)

**Comment by Sara-Araibi** [comment]
Drag and drop works now as well as copy and paste
