### ISSUE TITLE
Bug: Start and help button do not do anything

### ISSUE THREAD

**Issue by h-adil** [Vishwa061/2311-Group-12#5]
### Name
_Useless Buttons_
### Description
_The 'Start' and 'Help' buttons have no use in this system. It was stated in the user manual that the Start button should be clicked first to begin the system, and in doing so it would show a slightly different screen. The Help button should also work._ 
### Steps to reproduce 
_Open Convertron, then click the 'Start' button, then click the 'Help' button._
### Expected result 
_The Start button should show a slightly different screen, the Convert and Save button, alongside the features down the middle should go away. The Help button should do what it is supposed to do and give some advice to the user._
### Actual result
_Upon clicking the Start button, nothing happens. The screen does not change at all. The same thing happens with the Help button, there is no prompt or pop-up page or advice given to the user._
### Input used
_No input needed._
### Priority 
_Medium/High._
### Status 
_Ready for development._
### Screenshot 1
_What it should look like after clicking 'Start'_ <br/>
<img width="692" alt="Screen Shot 2021-03-20 at 5 18 22 PM" src="https://user-images.githubusercontent.com/76922658/111885870-ba66bd00-89a0-11eb-8958-4c85248877af.png"><br/>
### Screenshot 2
_What it actually looks like after clicking 'Start'_ <br/>
<img width="953" alt="Screen Shot 2021-03-20 at 5 19 11 PM" src="https://user-images.githubusercontent.com/76922658/111885893-d4080480-89a0-11eb-9858-cb004818e2de.png"><br/>
### Screenshot 3
_Help button does not work_ <br/>
<img width="151" alt="Screen Shot 2021-03-20 at 5 19 17 PM" src="https://user-images.githubusercontent.com/76922658/111885909-ee41e280-89a0-11eb-87e5-a8c67e5d52d1.png">

**Comment by Sara-Araibi** [comment]
Help and start button works
