### ISSUE TITLE
Bug: Specify Title, Specify Composer, Select Key and Select Time Signature are not functioning

### ISSUE THREAD

**Issue by aman9824** [Vishwa061/2311-Group-12#8]
**Title:**

Specify Title, Specify Composer, Select Key and Select Time Signature are not functioning

**Reported By:**

Aman Patel

**Version:**

Commit ID: 1613ddb62e4b46757bdf313fec348d32e07c511d

**Platform:**

macOS
Java SE-15
Eclipse

**Reproduction:**

Open the Convertron as stated in User Manual and then click on the "Specify Title", "Specify Composer", "Select Key", and "Select Time Signature" for functionality.

**Actual Result:**

Upon clicking either of the buttons, Nothing was working. The text in the text editor of UI stays the same.

**Expected Result:**

There was nothing written about expected output in the User Manual but it should specify the music tab composer Name, tab title and should be able to handle the selection process of Keys and Time Signature.

**Priority:**

Medium

**Severity:**

Medium

**Screenshot:**

<img width="218" alt="Screen Shot 2021-03-23 at 10 40 36 PM" src="https://user-images.githubusercontent.com/57772408/112247982-8fdc6480-8c2b-11eb-9fad-69691e17002d.png">

**Comment by Sara-Araibi** [comment]
all works and are functionable
