### ISSUE TITLE
Unexpected Dummy output for XML

### ISSUE THREAD

**Issue by mike-jshen** [Vishwa061/2311-Group-12#9]
Tested on: Windows 10 Java SE 1.8
Bug Report 1: Unexpected Dummy output for XML

Severity: Medium (Expected output is not achieved)
Priority: HIGH
Version: 8f22041
Description:
When converting a demo xml file, it appears that the output XML is a dummy output. Extended testing with various types of text inputs for tabs yield the same XML output. 

Comments:
Other modified tablatures seem to have no effect with the xml output. This appears to be an issue with the code and how the data is taken. When testing for drums and bass, the same result was given.

Attachments:
![image](https://user-images.githubusercontent.com/68671792/112345073-1bd9a500-8c9b-11eb-8857-082918bceaf0.png)

![image](https://user-images.githubusercontent.com/68671792/112345108-21cf8600-8c9b-11eb-8cbf-73139e69441e.png)

The following xml output circled in red yields the tablature in the picture below.

**Comment by Sara-Araibi** [comment]
Uploading any tablature will give the right upload now
